document.addEventListener('DOMContentLoaded', () => {
  const db = window.supabase.createClient(SUPABASE_URL, SUPABASE_ANON_KEY);
  const $ = id => document.getElementById(id);
  const root = document.documentElement;
  const layout = document.querySelector('.layout');
  const euro = n => `${Number(n || 0).toFixed(2)} EUR`;
  const toLocalISO = d => `${d.getFullYear()}-${String(d.getMonth() + 1).padStart(2, '0')}-${String(d.getDate()).padStart(2, '0')}`;
  const dateNow = () => toLocalISO(new Date());
  const safe = v => String(v ?? '').replace(/[&<>"']/g, c => ({'&': '&amp;', '<': '&lt;', '>': '&gt;', '"': '&quot;', "'": '&#39;'}[c]));
  const titles = {dashboard:'Tableau de bord', calendrier:'Calendrier', ecuries:'Ecuries', cavaliers:'Cavalier(e)s', shootings:'Shootings', prestations:'Grille tarifaire', facturation:'Creer une facture', factures:'Factures emises', reglages:'Reglages'};
  let settings = {id:null, nom_entreprise:'', adresse:'', code_postal_entreprise:'', ville_entreprise:'', siret:'', logo_url:'', domicile_adresse:'', domicile_latitude:null, domicile_longitude:null, puissance_fiscale_cv:4, taux_km:.606, mention_tva:'TVA non applicable, art. 293 B du CGI', prefixe_facture:'FACT-2026-', prochain_numero_facture:1, vehicule_marque:'', vehicule_modele:'', vehicule_annee:null, vehicule_energie:'essence', rappels_jours:[30,14,7,2,1], rappel_affichage_limite:3, types_paiement:['espece','cheque','virement','sans_contact'], shootings_afficher_a_venir:true};
  let chart=null, map=null, currentEcurie=null, currentCavaliere=null, currentShooting=null, currentService=null, ecuries=[], cavaliers=[], shootings=[], services=[], calCursor=new Date(), bellItemsCache=[], unpaidItems=[];
  const defaultIcons={dashboard:'bx bx-home-circle', calendrier:'bx bx-calendar', ecuries:'bx bx-buildings', cavaliers:'bx bx-group', shootings:'bx bx-camera-movie', prestations:'bx bx-camera', facturation:'bx bx-receipt', factures:'bx bx-file', reglages:'bx bx-cog'};
  const lightPalettes={classic:{'--bg-body':'#F5F6F8'}}, darkPalettes={classic:{'--bg-body':'#1A1F2B'}}, themeColorLabels={'--bg-body':'Fond général'};
  function getIcons(){try{return JSON.parse(localStorage.getItem('boxicons_menu'))||{}}catch{return{}}} function applyIcons(){} function initIconFields(){} function getThemePaletteOverrides(){try{return JSON.parse(localStorage.getItem('themePaletteOverrides')||'{}')}catch{return{}}} function saveThemePaletteOverrides(o){localStorage.setItem('themePaletteOverrides',JSON.stringify(o))} function getPaletteColors(){return{}} function applyPaletteColors(){} function renderThemeColorFields(){} function resetThemeColors(){} function setTheme(){} function setColorTheme(){} function setLayout(){} function setSidebar(){} function closeMenus(){} function openTab(name){document.querySelector(`#tabs button[data-tab="${name}"]`)?.click()} function loadLocalProfile(){}
  async function loadShootings(){const{data,error}=await db.from('concours').select('*,ecuries(nom),cavalieres(nom,prenom)').order('date_debut');if(error)return console.error(error);shootings=data||[];renderShootingsTable();refreshBell();renderCalendar()}
  function shootingIsUpcoming(s){return(s.date_fin||s.date_debut)>=dateNow()}
  function renderShootingsTable(){const table=$('table-shootings');if(!table)return;const only=$('filtre-shootings-a-venir')?.checked??settings.shootings_afficher_a_venir??true;const list=only?shootings.filter(shootingIsUpcoming):shootings;table.querySelector('tbody').innerHTML=list.map(s=>`<tr data-shooting-id="${s.id}"><td>${safe(s.nom)}</td><td>${s.type_shooting==='concours'?'Concours':'Shooting perso.'}</td><td>${safe(s.ecuries?.nom||s.lieu||'-')}</td><td>${s.cavalieres?`${safe(s.cavalieres.prenom)} ${safe(s.cavalieres.nom)}`:'-'}</td><td>${safe(s.date_debut)}${s.date_fin&&s.date_fin!==s.date_debut?` -> ${safe(s.date_fin)}`:''}</td><td><span class="badge-statut badge-${shootingIsUpcoming(s)?'a-venir':'termine'}">${shootingIsUpcoming(s)?'A venir':'Termine'}</span></td><td><button data-edit-shooting="${s.id}">Modifier</button><button class="btn-danger" data-delete-shooting="${s.id}">Supprimer</button></td></tr>`).join('')||'<tr><td colspan="7">Aucun shooting correspondant</td></tr>';document.querySelectorAll('[data-edit-shooting]').forEach(b=>b.onclick=()=>editShooting(b.dataset.editShooting));document.querySelectorAll('[data-delete-shooting]').forEach(b=>b.onclick=()=>deleteShooting(b.dataset.deleteShooting))}
  $('filtre-shootings-a-venir')?.addEventListener('change',renderShootingsTable);
  $('form-reglages')?.addEventListener('submit',async e=>{e.preventDefault();const p={shootings_afficher_a_venir:$('rg-shootings-a-venir')?.checked??true};await db.from('reglages').update(p).eq('id',settings.id);await loadSettings();renderShootingsTable()});
  async function init(){await loadSettings();await loadShootings();await loadServices();await loadInvoices();await loadDashboard();await refreshUnpaid();renderCalendar()} init();
});