document.addEventListener('DOMContentLoaded', () => {
  const $ = id => document.getElementById(id);
  const state = { db: null, ecuries: [], cavalieres: [], concours: [], factures: [] };
  const titles = { dashboard:'Tableau de bord', ecuries:'Écuries', cavalieres:'Cavalières', concours:'Concours', prestations:'Grille tarifaire', facturation:'Créer une facture', factures:'Factures émises', reglages:'Réglages' };
  function setStatus(kind, message) { const box = $('connection-status'); if (!box) return; box.className = `connection-status ${kind}`; const icon = kind === 'ok' ? 'bx-check-circle' : kind === 'error' ? 'bx-error-circle' : 'bx-loader-alt bx-spin'; box.innerHTML = `<i class="bx ${icon}"></i><span>${message}</span>`; }
  function text(id, value) { const el = $(id); if (el) el.textContent = value; }
  function euro(value) { return `${Number(value || 0).toFixed(2).replace('.', ',')} €`; }
  function errorMessage(error) { return error?.message || error?.details || error?.hint || 'Erreur inconnue'; }
  function closeUserMenu() { $('user-menu')?.classList.remove('open'); }
  document.querySelectorAll('#tabs button[data-tab]').forEach(button => button.addEventListener('click', () => { document.querySelectorAll('#tabs button[data-tab]').forEach(item => item.classList.remove('active')); document.querySelectorAll('.tab').forEach(item => item.classList.remove('active')); button.classList.add('active'); $(button.dataset.tab)?.classList.add('active'); text('page-title', titles[button.dataset.tab] || 'ShootnLook'); document.body.classList.remove('menu-open'); closeUserMenu(); }));
  $('sidebar-toggle')?.addEventListener('click', () => document.body.classList.toggle('menu-open'));
  $('sidebar-backdrop')?.addEventListener('click', () => document.body.classList.remove('menu-open'));
  $('user-toggle')?.addEventListener('click', event => { event.stopPropagation(); $('user-menu')?.classList.toggle('open'); });
  document.addEventListener('click', event => { if (!event.target.closest('.topbar-menu-wrap')) closeUserMenu(); });
  $('edit-profile-btn')?.addEventListener('click', () => { closeUserMenu(); $('profile-modal')?.classList.add('visible'); });
  $('open-profile-modal')?.addEventListener('click', () => $('profile-modal')?.classList.add('visible'));
  $('close-profile-modal')?.addEventListener('click', () => $('profile-modal')?.classList.remove('visible'));
  document.querySelectorAll('[data-open-tab]').forEach(button => button.addEventListener('click', () => document.querySelector(`#tabs button[data-tab="${button.dataset.openTab}"]`)?.click()));
  function loadLocalProfile() { const name = localStorage.getItem('profil_pseudo') || 'Admin'; ['dashboard-user-name','menu-user-name'].forEach(id => text(id, name)); document.querySelectorAll('.user-avatar').forEach(el => el.textContent = name.charAt(0).toUpperCase()); ['pf-pseudo','pf-societe','pf-adresse','pf-code-postal','pf-ville'].forEach(id => { const el = $(id); if (el) el.value = localStorage.getItem(`profil_${id.replace('pf-','')}`) || ''; }); }
  $('form-profil')?.addEventListener('submit', event => { event.preventDefault(); const fields = { pseudo: $('pf-pseudo').value.trim() || 'Admin', societe: $('pf-societe').value.trim(), adresse: $('pf-adresse').value.trim(), code_postal: $('pf-code-postal').value.trim(), ville: $('pf-ville').value.trim() }; Object.entries(fields).forEach(([key, value]) => localStorage.setItem(`profil_${key}`, value)); loadLocalProfile(); $('profile-modal')?.classList.remove('visible'); });
  async function selectAll(table, order) { let query = state.db.from(table).select('*'); if (order) query = query.order(order); const { data, error } = await query; if (error) throw new Error(`${table} : ${errorMessage(error)}`); return data || []; }
  async function loadData() { setStatus('loading', 'Connexion à la base de données…'); if (!window.supabase || typeof SUPABASE_URL === 'undefined' || typeof SUPABASE_ANON_KEY === 'undefined') throw new Error('Supabase ou config.js n’est pas chargé.'); state.db = window.supabase.createClient(SUPABASE_URL, SUPABASE_ANON_KEY); const results = await Promise.all([selectAll('ecuries', 'nom'), selectAll('cavalieres', 'nom'), selectAll('concours', 'date_debut'), selectAll('factures', 'date_creation')]); [state.ecuries, state.cavalieres, state.concours, state.factures] = results; const paid = state.factures.filter(f => String(f.statut_paiement || f.statut || '').toLowerCase() === 'payee'); const pending = state.factures.filter(f => ['en_attente','en_retard','pending'].includes(String(f.statut_paiement || f.statut || '').toLowerCase())); const now = new Date(); const monthly = paid.filter(f => { const d = new Date(f.date_creation || f.date || f.created_at); return !Number.isNaN(d) && d.getMonth() === now.getMonth() && d.getFullYear() === now.getFullYear(); }).reduce((sum, f) => sum + Number(f.montant_total || f.montant || 0), 0); text('dash-total-ecuries', state.ecuries.length); text('dash-total-cavalieres', state.cavalieres.length); text('dash-en-attente', pending.length); text('dash-ca-mois', euro(monthly)); text('ecuries-summary', `${state.ecuries.length} écurie(s) chargée(s) depuis Supabase.`); text('cavalieres-summary', `${state.cavalieres.length} cavalière(s) chargée(s) depuis Supabase.`); text('concours-summary', `${state.concours.length} concours chargé(s) depuis Supabase.`); text('factures-summary', `${state.factures.length} facture(s) chargée(s) depuis Supabase.`); text('sync-summary', `Connexion réussie : ${state.ecuries.length} écurie(s), ${state.cavalieres.length} cavalière(s), ${state.concours.length} concours et ${state.factures.length} facture(s) ont été lus.`); setStatus('ok', 'Connexion Supabase établie. Les données sont synchronisées.'); }
  async function start() { loadLocalProfile(); try { await loadData(); } catch (error) { console.error(error); setStatus('error', `Connexion impossible : ${error.message}`); text('sync-summary', 'Les données ne sont pas accessibles. Vérifie les politiques RLS et les noms des tables dans Supabase.'); ['dash-total-ecuries','dash-total-cavalieres','dash-en-attente'].forEach(id => text(id, '—')); text('dash-ca-mois', '—'); } }
  $('retry-connection')?.addEventListener('click', start); start();
});
