import { chromium } from 'playwright';
const browser = await chromium.launch({ headless: true });
const page = await browser.newPage();
await page.goto('http://localhost:8000/index.modular.html');
await page.waitForTimeout(1200);
console.log('USER_NAME=' + await page.locator('#topbar-user-name').textContent());
console.log('PROFILE_MODAL_DISPLAY=' + await page.locator('#profile-modal').evaluate(el => getComputedStyle(el).display));
await page.locator('#user-toggle').click();
await page.locator('#edit-profile-btn').click();
console.log('PROFILE_MODAL_AFTER_CLICK=' + await page.locator('#profile-modal').evaluate(el => getComputedStyle(el).display));
await page.fill('#pf-pseudo', 'Nouveau Nom');
await page.fill('#pf-societe', 'Nouvelle Société');
await page.fill('#pf-adresse', '12 rue test');
await page.fill('#pf-code-postal', '75001');
await page.fill('#pf-ville', 'Paris');
await page.locator('#form-profil button[type="submit"]').click();
console.log('USER_NAME_AFTER_SUBMIT=' + await page.locator('#topbar-user-name').textContent());
console.log('LOCAL_STORAGE=' + JSON.stringify(await page.evaluate(() => ({ pseudo: localStorage.getItem('profil_pseudo'), societe: localStorage.getItem('profil_societe'), adresse: localStorage.getItem('profil_adresse'), cp: localStorage.getItem('profil_code_postal'), ville: localStorage.getItem('profil_ville') }))));
await page.locator('#user-toggle').click();
await page.locator('[data-open-tab="reglages"]').click();
console.log('PAGE_TITLE=' + await page.locator('#page-title').textContent());
console.log('SETTINGS_ACTIVE=' + await page.locator('#reglages').evaluate(el => el.classList.contains('active')));
await browser.close();
